### ISSUE TITLE
Error when using x-hidden: Laravel returns "View [bootstrap-4.components.forms.inputs.hidden] not found"

### ISSUE THREAD

**Issue by tititoof** [forxer/blade-ui-kit-bootstrap#14]
Description:
I encountered an error while using the x-hidden input. 
Laravel is returning the following error message: "View [bootstrap-4.components.forms.inputs.hidden] not found". 
It seems that Laravel is unable to locate the specified view.

Steps to reproduce:

Add the x-hidden element.
Observe the error message displayed.

<x-hidden name="toto"/>

Error message :
View [bootstrap-4.components.forms.inputs.hidden] not found.

Additional information:

Laravel version: 10.13.5
Relevant code snippets or configurations: 

Please let me know if there is any further information needed.

**Comment by forxer** [comment]
Ah yes necessarily if I forget to put the view, it is not likely to work. I fix that in the next version, thanks.

**Comment by forxer** [comment]
fixed in 0.7.0
